export const SEED_POSTS: Array<{ number: string; title: string }> = [
  { number: "1", title: "When Inconsistent Messaging Becomes a Regulatory Risk" },
  { number: "2", title: "Why Allocators Are Backing Distress Over Stability" },
  { number: "3", title: "The Rise of Private Credit and What It Means for Today's Managers" },
  { number: "4", title: "Why Companies Now Skip Public Markets for Private Financing" },
  { number: "5", title: "How to Evaluate a Private Equity Web Design Agency" },
  { number: "7", title: "Strategic Capital in Defense Tech: How Corporate Money Is Reshaping Deal Access, Process, and Exits" },
  { number: "8", title: "Why Big Healthcare Buyers Are Racing to Lock Up Critical Assets" },
  { number: "9", title: "Green Certification Becomes the Price of Market Access" },
  { number: "10", title: "Best Hedge Fund Website Design Agencies" },
  { number: "11", title: "Silver's Two Prices and the Risk No One Is Modeling" },
  { number: "12", title: "Strategic Capital in Defense Tech: How Corporate Money Is Reshaping" },
  { number: "13", title: "Why Big Healthcare Buyers Are Racing to Lock Up Critical Assets" },
  { number: "14", title: "Best Hedge Fund Website Design Agencies" },
  { number: "15", title: "Green Certification Becomes the Price of Market Access" },
  { number: "16", title: "8 Questions to Ask Before Hiring a Real Estate Web Designer" },
  { number: "17", title: "EA's $55 Billion Buyout and What it Means for PE Fund Math" },
  { number: "18", title: "The Counterintuitive Rules That Make VC Websites Work in 2026" },
  { number: "19", title: "Secrets of Top Hedge Fund Websites" },
  { number: "20", title: "How Institutional Allocators Evaluate Real Estate Firm Websites" },
  { number: "21", title: "Why Timing the Exit in Private Equity Is the New Competitive Advantage" },
  { number: "22", title: "What Alphabet's $4 Trillion Valuation Reveals About AI Investment" },
  { number: "23", title: "How to Build a Content Plan for a Financial Services Firm" },
  { number: "24", title: "Top 5 Financial Services Marketing Agencies (How to Identify Real Fluency)" },
  { number: "25", title: "Which Marketing Strategies Are Most Effective in Financial Services" },
  { number: "26", title: "The 5 Best Digital Marketing Agencies for Consulting Firms" },
  { number: "27", title: "How AI is Reshaping Real Estate Underwriting and Due Diligence" },
  { number: "28", title: "What Digital Marketing Does for Consulting Firms" },
  { number: "29", title: "What the Decline of Fund-of-Funds Says About the Evolution of Institutional Investors" },
  { number: "30", title: "Why Private Markets Firms Are Buying Capabilities, Not Just Assets" },
  { number: "31", title: "Embedded From The Start: How Integrated Communications Support Changes What's Possible At Every Stage" },
  { number: "32", title: "What Makes a GP Newsletter Actually Work" },
  { number: "33", title: "Exit Optionality and the BitGo IPO" },
  { number: "34", title: "The AI Research Layer That Runs Before Anyone Reads Your Deck" },
  { number: "34.2", title: "The AI Research Layer That Runs Before Anyone Reads Your Deck" },
  { number: "35", title: "The Memo That Preceded the Capital: What Howard Marks Built Before Oaktree Needed It" },
  { number: "36", title: "Real Estate Investment Firm Branding: How Institutional Investors Evaluate Credibility and Choose Managers" },
  { number: "37", title: "Rebranding Plan After Private Equity Acquisition: The Execution Model for Scaling Portfolio Companies" },
  { number: "38", title: "Content Marketing for Financial Services: What It's For and When It Works" },
  { number: "39", title: "Post-Acquisition Brand Strategy for Private Equity: Architecture, Timing, and Execution Discipline" },
  { number: "40", title: "Top Private Equity Branding Agencies: A Framework for Evaluating Roll-Up and Fund-Level Communications Partners" },
  { number: "41", title: "When the Founder Leaves: What Actually Survives a Succession in Private Markets" },
  { number: "42", title: "Millennium Management: When the Brand Is the Machine, Not the Manager" },
  { number: "43", title: "When the CRE Loans Come Due, So Does the LP" },
  { number: "45", title: "Why Finance Firms Lose Deals to Competitors Who Look More Professional" },
  { number: "46", title: "How Private Equity Firms Are Using Brand Strategy to Win More Mandates" },
  { number: "47", title: "13 Questions Every First-Time Fund Manager Must Answer Before a Capital Raise" },
  { number: "48", title: "10 Questions Every Fund Manager Should Be Able to Answer Before a Capital Raise" },
  { number: "49", title: "Best Website Design Agencies for Portfolio Companies: How to Identify a Partner That Can Operate in a PE-backed Environment" },
  { number: "50", title: "What to Do in a Winner-Takes-Most Market" },
  { number: "51", title: "The Acquisition Opportunity Hiding in Plain Sight" },
  { number: "52", title: "Why the Bezos-Musk Rivalry Could Reshape Entire Markets" },
  { number: "53", title: "High Oil Prices Are Turning Into a Financing Squeeze" },
  { number: "54", title: "OpenAI's Valuation is Being Repriced on Coherence, Not Capital" },
  { number: "55", title: "Wall Street's Big Payday and What Bank Balance Sheets Now Reveal" },
];
